/* BootCfgParserTokenManager.java */
 /* Generated By:JavaCC: Do not edit this line. BootCfgParserTokenManager.java */
package com.github.alexfalappa.nbspringboot.cfgeditor.jcc;

/** Token Manager. */
@SuppressWarnings("unused")
public class BootCfgParserTokenManager implements BootCfgParserConstants {

    /** Debug output. */
    public java.io.PrintStream debugStream = System.out;

    /** Set debug output. */
    public void setDebugStream(java.io.PrintStream ds) {
        debugStream = ds;
    }

    private final int jjStopStringLiteralDfa_0(int pos, long active0) {
        switch (pos) {
            default:
                return -1;
        }
    }

    private final int jjStartNfa_0(int pos, long active0) {
        return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
    }

    private int jjStopAtPos(int pos, int kind) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        return pos + 1;
    }

    private int jjMoveStringLiteralDfa0_0() {
        switch (curChar) {
            case 46:
                return jjStartNfaWithStates_0(0, 7, 21);
            case 58:
                return jjStartNfaWithStates_0(0, 6, 21);
            case 61:
                return jjStartNfaWithStates_0(0, 5, 21);
            case 91:
                return jjStartNfaWithStates_0(0, 8, 21);
            case 93:
                return jjStartNfaWithStates_0(0, 9, 21);
            default:
                return jjMoveNfa_0(13, 0);
        }
    }

    private int jjStartNfaWithStates_0(int pos, int kind, int state) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return pos + 1;
        }
        return jjMoveNfa_0(state, pos + 1);
    }
    static final long[] jjbitVec0 = {
        0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
    };

    private int jjMoveNfa_0(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 22;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (;;) {
            if (++jjround == 0x7fffffff) {
                ReInitRounds();
            }
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 13:
                            if ((0xffffffff00000000L & l) != 0L) {
                                if (kind > 14) {
                                    kind = 14;
                                }
                                {
                                    jjCheckNAdd(21);
                                }
                            } else if ((0x2400L & l) != 0L) {
                                if (kind > 2) {
                                    kind = 2;
                                }
                            }
                            if ((0x3ff000000000000L & l) != 0L) {
                                if (kind > 12) {
                                    kind = 12;
                                }
                                {
                                    jjCheckNAdd(20);
                                }
                            } else if ((0x100003600L & l) != 0L) {
                                if (kind > 1) {
                                    kind = 1;
                                }
                                {
                                    jjCheckNAddStates(0, 6);
                                }
                            } else if (curChar == 33) {
                                jjCheckNAddStates(7, 9);
                            } else if (curChar == 35) {
                                jjCheckNAddStates(10, 12);
                            }
                            if ((0x3fe000000000000L & l) != 0L) {
                                jjCheckNAdd(14);
                            } else if (curChar == 13) {
                                jjstateSet[jjnewStateCnt++] = 1;
                            }
                            break;
                        case 0:
                            if ((0x2400L & l) != 0L && kind > 2) {
                                kind = 2;
                            }
                            break;
                        case 1:
                            if (curChar == 10 && kind > 2) {
                                kind = 2;
                            }
                            break;
                        case 2:
                            if (curChar == 13) {
                                jjstateSet[jjnewStateCnt++] = 1;
                            }
                            break;
                        case 3:
                            if (curChar == 35) {
                                jjCheckNAddStates(10, 12);
                            }
                            break;
                        case 4:
                            if ((0xffffffffffffdbffL & l) != 0L) {
                                jjCheckNAddStates(10, 12);
                            }
                            break;
                        case 5:
                            if ((0x2400L & l) != 0L && kind > 3) {
                                kind = 3;
                            }
                            break;
                        case 6:
                            if (curChar == 10 && kind > 3) {
                                kind = 3;
                            }
                            break;
                        case 7:
                            if (curChar == 13) {
                                jjstateSet[jjnewStateCnt++] = 6;
                            }
                            break;
                        case 8:
                            if (curChar == 33) {
                                jjCheckNAddStates(7, 9);
                            }
                            break;
                        case 9:
                            if ((0xffffffffffffdbffL & l) != 0L) {
                                jjCheckNAddStates(7, 9);
                            }
                            break;
                        case 10:
                            if ((0x2400L & l) != 0L && kind > 4) {
                                kind = 4;
                            }
                            break;
                        case 11:
                            if (curChar == 10 && kind > 4) {
                                kind = 4;
                            }
                            break;
                        case 12:
                            if (curChar == 13) {
                                jjstateSet[jjnewStateCnt++] = 11;
                            }
                            break;
                        case 14:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 12) {
                                kind = 12;
                            }
                             {
                                jjCheckNAdd(14);
                            }
                            break;
                        case 15:
                            if ((0x100003600L & l) == 0L) {
                                break;
                            }
                            if (kind > 1) {
                                kind = 1;
                            }
                             {
                                jjCheckNAddStates(0, 6);
                            }
                            break;
                        case 16:
                            if ((0x100003600L & l) != 0L) {
                                jjCheckNAddStates(13, 15);
                            }
                            break;
                        case 17:
                            if ((0x100003600L & l) != 0L) {
                                jjCheckNAddTwoStates(17, 3);
                            }
                            break;
                        case 18:
                            if ((0x100003600L & l) != 0L) {
                                jjCheckNAddTwoStates(18, 8);
                            }
                            break;
                        case 19:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 12) {
                                kind = 12;
                            }
                             {
                                jjCheckNAdd(20);
                            }
                            break;
                        case 20:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 13) {
                                kind = 13;
                            }
                             {
                                jjCheckNAdd(20);
                            }
                            break;
                        case 21:
                            if ((0xffffffff00000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 14) {
                                kind = 14;
                            }
                             {
                                jjCheckNAdd(21);
                            }
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 13:
                        case 21:
                            if ((0xffffffffefffffffL & l) == 0L) {
                                break;
                            }
                            if (kind > 14) {
                                kind = 14;
                            }
                             {
                                jjCheckNAdd(21);
                            }
                            break;
                        case 4: {
                            jjAddStates(10, 12);
                        }
                        break;
                        case 9: {
                            jjAddStates(7, 9);
                        }
                        break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else {
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 13:
                        case 21:
                            if ((jjbitVec0[i2] & l2) == 0L) {
                                break;
                            }
                            if (kind > 14) {
                                kind = 14;
                            }
                             {
                                jjCheckNAdd(21);
                            }
                            break;
                        case 4:
                            if ((jjbitVec0[i2] & l2) != 0L) {
                                jjAddStates(10, 12);
                            }
                            break;
                        case 9:
                            if ((jjbitVec0[i2] & l2) != 0L) {
                                jjAddStates(7, 9);
                            }
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 22 - (jjnewStateCnt = startsAt))) {
                return curPos;
            }
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }
    static final int[] jjnextStates = {
        16, 0, 2, 17, 3, 18, 8, 9, 10, 12, 4, 5, 7, 16, 0, 2,};

    /** Token literal values. */
    public static final String[] jjstrLiteralImages = {
        "", null, null, null, null, "\75", "\72", "\56", "\133", "\135", null, null,
        null, null, null, null,};

    protected Token jjFillToken() {
        final Token t;
        final String curTokenImage;
        final int beginLine;
        final int endLine;
        final int beginColumn;
        final int endColumn;
        if (jjmatchedPos < 0) {
            if (image == null) {
                curTokenImage = "";
            } else {
                curTokenImage = image.toString();
            }
            beginLine = endLine = input_stream.getEndLine();
            beginColumn = endColumn = input_stream.getEndColumn();
        } else {
            String im = jjstrLiteralImages[jjmatchedKind];
            curTokenImage = (im == null) ? input_stream.GetImage() : im;
            beginLine = input_stream.getBeginLine();
            beginColumn = input_stream.getBeginColumn();
            endLine = input_stream.getEndLine();
            endColumn = input_stream.getEndColumn();
        }
        t = Token.newToken(jjmatchedKind, curTokenImage);

        t.beginLine = beginLine;
        t.endLine = endLine;
        t.beginColumn = beginColumn;
        t.endColumn = endColumn;

        return t;
    }

    int curLexState = 0;
    int defaultLexState = 0;
    int jjnewStateCnt;
    int jjround;
    int jjmatchedPos;
    int jjmatchedKind;

    /** Get the next Token. */
    public Token getNextToken() {
        Token matchedToken;
        int curPos = 0;

        EOFLoop:
        for (;;) {
            try {
                curChar = input_stream.BeginToken();
            } catch (Exception e) {
                jjmatchedKind = 0;
                jjmatchedPos = -1;
                matchedToken = jjFillToken();
                return matchedToken;
            }
            image = jjimage;
            image.setLength(0);
            jjimageLen = 0;

            jjmatchedKind = 14;
            jjmatchedPos = -1;
            curPos = 0;
            curPos = jjMoveStringLiteralDfa0_0();
            if (jjmatchedKind != 0x7fffffff) {
                if (jjmatchedPos + 1 < curPos) {
                    input_stream.backup(curPos - jjmatchedPos - 1);
                }
                matchedToken = jjFillToken();
                TokenLexicalActions(matchedToken);
                return matchedToken;
            }
            int error_line = input_stream.getEndLine();
            int error_column = input_stream.getEndColumn();
            String error_after = null;
            boolean EOFSeen = false;
            try {
                input_stream.readChar();
                input_stream.backup(1);
            } catch (java.io.IOException e1) {
                EOFSeen = true;
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
                if (curChar == '\n' || curChar == '\r') {
                    error_line++;
                    error_column = 0;
                } else {
                    error_column++;
                }
            }
            if (!EOFSeen) {
                input_stream.backup(1);
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
            }
            throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
        }
    }

    int[] jjemptyLineNo = new int[1];
    int[] jjemptyColNo = new int[1];
    boolean[] jjbeenHere = new boolean[1];

    void TokenLexicalActions(Token matchedToken) {
        switch (jjmatchedKind) {
            case 0:
                break;
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                break;
            case 5:
                break;
            case 6:
                break;
            case 7:
                break;
            case 8:
                break;
            case 9:
                break;
            case 12:
                break;
            case 13:
                break;
            case 14:
                if (jjmatchedPos == -1) {
                    if (jjbeenHere[0]
                            && jjemptyLineNo[0] == input_stream.getBeginLine()
                            && jjemptyColNo[0] == input_stream.getBeginColumn()) {
                        throw new TokenMgrError(
                                ("Error: Bailing out of infinite loop caused by repeated empty string matches at line " + input_stream
                                        .getBeginLine() + ", column " + input_stream.getBeginColumn() + "."), TokenMgrError.LOOP_DETECTED);
                    }
                    jjemptyLineNo[0] = input_stream.getBeginLine();
                    jjemptyColNo[0] = input_stream.getBeginColumn();
                    jjbeenHere[0] = true;
                }
                break;
            case 15:
                break;
            default:
                break;
        }
    }

    private void jjCheckNAdd(int state) {
        if (jjrounds[state] != jjround) {
            jjstateSet[jjnewStateCnt++] = state;
            jjrounds[state] = jjround;
        }
    }

    private void jjAddStates(int start, int end) {
        do {
            jjstateSet[jjnewStateCnt++] = jjnextStates[start];
        } while (start++ != end);
    }

    private void jjCheckNAddTwoStates(int state1, int state2) {
        jjCheckNAdd(state1);
        jjCheckNAdd(state2);
    }

    private void jjCheckNAddStates(int start, int end) {
        do {
            jjCheckNAdd(jjnextStates[start]);
        } while (start++ != end);
    }

    /** Constructor. */
    public BootCfgParserTokenManager(SimpleCharStream2 stream) {

        if (SimpleCharStream2.staticFlag) {
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
        }

        input_stream = stream;
    }

    /** Constructor. */
    public BootCfgParserTokenManager(SimpleCharStream2 stream, int lexState) {
        ReInit(stream);
        SwitchTo(lexState);
    }

    /** Reinitialise parser. */
    public void ReInit(SimpleCharStream2 stream) {

        jjmatchedPos = jjnewStateCnt = 0;
        curLexState = defaultLexState;
        input_stream = stream;
        ReInitRounds();
    }

    private void ReInitRounds() {
        int i;
        jjround = 0x80000001;
        for (i = 22; i-- > 0;) {
            jjrounds[i] = 0x80000000;
        }
    }

    /** Reinitialise parser. */
    public void ReInit(SimpleCharStream2 stream, int lexState) {

        ReInit(stream);
        SwitchTo(lexState);
    }

    /** Switch to specified lex state. */
    public void SwitchTo(int lexState) {
        if (lexState >= 1 || lexState < 0) {
            throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.",
                    TokenMgrError.INVALID_LEXICAL_STATE);
        } else {
            curLexState = lexState;
        }
    }

    /** Lexer state names. */
    public static final String[] lexStateNames = {
        "DEFAULT",};
    protected SimpleCharStream2 input_stream;

    private final int[] jjrounds = new int[22];
    private final int[] jjstateSet = new int[2 * 22];

    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;

    protected int curChar;
}
