/* Generated By:JavaCC: Do not edit this line. BootCfgParserConstants.java */
package com.github.alexfalappa.nbspringboot.cfgeditor.jcc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BootCfgParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int BLANK_LINE = 2;
  /** RegularExpression Id. */
  int COMMENT_LINE1 = 3;
  /** RegularExpression Id. */
  int COMMENT_LINE2 = 4;
  /** RegularExpression Id. */
  int O_EQUAL = 5;
  /** RegularExpression Id. */
  int O_COLON = 6;
  /** RegularExpression Id. */
  int O_DOT = 7;
  /** RegularExpression Id. */
  int O_OPENBRACKET = 8;
  /** RegularExpression Id. */
  int O_CLOSEBRACKET = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int NONZERO_DIGIT = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int DIGITS = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int ALLOWABLE_CHARACTERS = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<BLANK_LINE>",
    "<COMMENT_LINE1>",
    "<COMMENT_LINE2>",
    "\"=\"",
    "\":\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "<DIGIT>",
    "<NONZERO_DIGIT>",
    "<INTEGER>",
    "<DIGITS>",
    "<STRING>",
    "<ALLOWABLE_CHARACTERS>",
  };

}
